### ISSUE TITLE
Training loss backpropagation error

### ISSUE THREAD

**Issue by sainivedh19pt** [evanmy/sae#5]
Getting this when I run using **python train.py 0 2 --beta 0**

Traceback (most recent call last):
  File "train.py", line 312, in <module>
    compute_dice= args.compute_dice)
  File "train.py", line 153, in run
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: function EnforcePriorBackward returned an incorrect number of gradients (expected 2, got 1)

**Comment by sainivedh19pt** [comment]
working when Added the [return statement to ,None](https://github.com/evanmy/sae/blob/b2fe7c46d9e1561e93e39acb29c1b9a123df951a/functions/models.py#L102).

Did I solve the issue correctly ?!

**Comment by evanmy** [comment]
Hi, what version of torch you using? the model was tested on 1.1
